# Sample docker compose file

version: '3.9'

services:
  nfs:
    container_name: $CONTAINER_NAME
    image: $IMAGE:$VERSION
    restart: unless-stopped
    privileged: true
    volumes:
      - ./volumes/share:/share
      - ./config/etc/exports:/etc/exports
    ports:
      - 2049:2049
#    network: host

~                                                                          
