FROM golang:1.18.4-alpine as builder

RUN apk add git && \
    git clone https://github.com/GoogleCloudPlatform/gcsfuse.git && cd gcsfuse && \
    go install ./tools/build_gcsfuse && \
    build_gcsfuse . /tmp $(git log -1 --format=format:"%H")

FROM alpine:3.17

RUN apk add --update --no-cache fuse

COPY --from=builder /tmp/bin/gcsfuse /usr/local/bin/gcsfuse
COPY --from=builder /tmp/sbin/mount.gcsfuse /usr/sbin/mount.gcsfuse

ENTRYPOINT /nfs/scripts/startup-gcs.sh && sleep infinity
