# Sample docker compose file

version: '3'

services:
  nfs:
    container_name: ${_CONTAINER_NAME}
    image: ${_REGISTRY}/${_IMAGE}:${TAG_NAME}${_TAG_SUFFIX}
    #image: ${_IMAGE}:${TAG_NAME}${_TAG_SUFFIX}
    restart: unless-stopped
    privileged: true
    #volumes:
    #  - ./volumes/share:/share
    #  - ./config/etc/exports:/etc/exports
    #  - ./scripts/startup-gcs.sh:/usr/local/bin/startup-gcs.sh
    ports:
      - 2049:2049
#    network: host
